-- Ruleaza in Supabase SQL Editor
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  full_name text not null,
  role text not null check (role in ('teacher', 'student')),
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  subject_slug text not null,
  title text not null,
  description text,
  event_date date not null,
  status text not null check (status in ('upcoming', 'past')),
  image_url text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.awards (
  id bigint generated by default as identity primary key,
  subject_slug text not null,
  title text not null,
  description text,
  award_type text not null default 'prize' check (award_type in ('prize', 'diploma', 'certificate', 'other')),
  year int,
  recipient text,
  image_url text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_events_subject on public.events(subject_slug);
create index if not exists idx_events_status on public.events(status);
create index if not exists idx_events_date on public.events(event_date);
create index if not exists idx_awards_subject on public.awards(subject_slug);

-- Optional: dezactivezi accesul public direct din client
alter table public.users enable row level security;
alter table public.events enable row level security;
alter table public.awards enable row level security;

-- Politici restrictive (backend foloseste service role, bypass RLS)
drop policy if exists "deny all users" on public.users;
create policy "deny all users" on public.users for all to public using (false) with check (false);

drop policy if exists "deny all events" on public.events;
create policy "deny all events" on public.events for all to public using (false) with check (false);

drop policy if exists "deny all awards" on public.awards;
create policy "deny all awards" on public.awards for all to public using (false) with check (false);

-- Migrare pentru proiecte create înainte de câmpul image_url
alter table public.events add column if not exists image_url text;
alter table public.awards add column if not exists image_url text;

-- Bucket public pentru fotografii (nume implicit: comisia-media)
insert into storage.buckets (id, name, public)
values ('comisia-media', 'comisia-media', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "comisia media public read" on storage.objects;
create policy "comisia media public read"
on storage.objects for select
to public
using (bucket_id = 'comisia-media');
